# 2.2 数据操作

In [1]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.6.0


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.6675e+21, 4.5730e-41, 1.6105e-38],
        [3.0858e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


创建一个5x3的随机初始化的`Tensor`:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])




创建一个5x3的long型全0的`Tensor`:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])




创建一个5x3的long型全1的`Tensor`:



In [5]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


创建一个单位矩阵：



In [6]:
x = torch.eye(4, 4, dtype=torch.int)
print(x)

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]], dtype=torch.int32)


In [7]:
# 从s到e，步长为step
x = torch.arange(1, 100, 2)
print(x)

x = torch.arange(1, 5)
print(x)

# 从s到e，均匀切分成steps份
x = torch.linspace(1, 5, 10)
print(x)


tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])
tensor([1, 2, 3, 4])
tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])





randperm（m）：随机打乱一个数字序列



In [8]:
x = torch.randperm(10)
print(x)

tensor([6, 1, 0, 7, 3, 2, 9, 5, 8, 4])


直接根据数据创建:

In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [10]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)

#below is wrong!
#x = torch.randn_like(x, dtype=torch.int)
#print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8567,  1.1006, -1.0712],
        [ 0.1227, -0.5663,  0.3731],
        [-0.8920, -1.5091,  0.3704],
        [ 1.4565,  0.9398,  0.7748],
        [ 0.1919,  1.2638, -1.2904]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [11]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算术操作
* **加法形式一**

In [12]:
x = torch.ones(5, 3)
print(x)
y = torch.rand(5, 3)
print(x + y)

y += 10.0
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.5932, 1.1123, 1.1535],
        [1.2417, 1.7262, 1.7011],
        [1.2038, 1.6511, 1.7745],
        [1.4369, 1.5191, 1.6159],
        [1.8102, 1.9801, 1.1147]])
tensor([[10.5932, 10.1123, 10.1535],
        [10.2417, 10.7262, 10.7011],
        [10.2038, 10.6511, 10.7745],
        [10.4369, 10.5191, 10.6159],
        [10.8102, 10.9801, 10.1147]])


* **加法形式二**

In [16]:
print(torch.add(x, y))

tensor([[12.5932, 12.1123, 12.1535],
        [12.2417, 12.7262, 12.7011],
        [12.2038, 12.6511, 12.7745],
        [12.4369, 12.5191, 12.6159],
        [12.8102, 12.9801, 12.1147]])


In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[12.5932, 12.1123, 12.1535],
        [12.2417, 12.7262, 12.7011],
        [12.2038, 12.6511, 12.7745],
        [12.4369, 12.5191, 12.6159],
        [12.8102, 12.9801, 12.1147]])


* **加法形式三、inplace**

In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[15.5932, 15.1123, 15.1535],
        [15.2417, 15.7262, 15.7011],
        [15.2038, 15.6511, 15.7745],
        [15.4369, 15.5191, 15.6159],
        [15.8102, 15.9801, 15.1147]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [23]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([3., 3., 3.])
tensor([3., 3., 3.])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [28]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [29]:
x += 1
print(x)
print(y) # 也加了1

tensor([[4., 4., 4.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([4., 4., 4., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [15]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.6035,  1.8110,  0.9549],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [36]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3354])
-0.33542600274086


线性代数运算

In [55]:
x = torch.randn(5,5)
print("x = ")
print(x)

#对角线元素之和(矩阵的迹)
print("x.trace = ")
print(torch.trace(x))

#对角线元素
print("x.diag = ")
print(torch.diag(x))

#矩阵的上三角/下三角，可指定偏移量
print("x.triu = ")
print(torch.triu(x))
print("x.tril = ")
print(torch.tril(x))

#矩阵乘法，batch的矩阵乘法
print("x * x = ")
print(x.mm(x))

#转置
print("x.t = ")
print(torch.t(x))

x = 
tensor([[ 0.7870,  0.1076, -1.0715, -0.1166, -1.0170],
        [-1.4453, -0.8078,  1.1975, -1.3700, -2.7575],
        [-0.8324,  0.4900,  0.2908,  0.6442,  3.9300],
        [-0.1244,  0.2953,  2.4197,  1.6456, -0.3087],
        [-1.5147,  1.9457, -1.2904, -2.3495, -2.0689]])
x.trace = 
tensor(-0.1532)
x.diag = 
tensor([ 0.7870, -0.8078,  0.2908,  1.6456, -2.0689])
x.triu = 
tensor([[ 0.7870,  0.1076, -1.0715, -0.1166, -1.0170],
        [ 0.0000, -0.8078,  1.1975, -1.3700, -2.7575],
        [ 0.0000,  0.0000,  0.2908,  0.6442,  3.9300],
        [ 0.0000,  0.0000,  0.0000,  1.6456, -0.3087],
        [ 0.0000,  0.0000,  0.0000,  0.0000, -2.0689]])
x.tril = 
tensor([[ 0.7870,  0.0000,  0.0000,  0.0000,  0.0000],
        [-1.4453, -0.8078,  0.0000,  0.0000,  0.0000],
        [-0.8324,  0.4900,  0.2908,  0.0000,  0.0000],
        [-0.1244,  0.2953,  2.4197,  1.6456,  0.0000],
        [-1.5147,  1.9457, -1.2904, -2.3495, -2.0689]])
x * x = 
tensor([[ 2.9106e+00, -2.5404e+00,  4.0367e-03,

## 2.2.3 广播机制

In [39]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [43]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
print(x)
print(y)
id_before = id(y)
print(id(x))
print(id(y))
y = y + x
print(id(y))
print(id(y) == id_before)

tensor([1, 2])
tensor([3, 4])
140161452039936
140161452122832
140161452103072
False


In [44]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
print(x)
print(y)
print(id(x))
print(id(y))
id_before = id(y)
y[:] = y + x
print(id(y))
print(id(y) == id_before)

tensor([1, 2])
tensor([3, 4])
140161467007456
140161452140176
140161452140176
True


In [45]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
print(x)
print(y)
print(id(x))
print(id(y))
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y))
print(id(y) == id_before)

tensor([1, 2])
tensor([3, 4])
140161452402320
140161452150368
140161452150368
True


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是使用的相同的内存，改变其中一个时另一个也会改变！！！**
### `Tensor`转NumPy

In [56]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [58]:
import numpy as np
a = np.ones(3)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1.] tensor([1., 1., 1.], dtype=torch.float64)
[2. 2. 2.] tensor([2., 2., 2.], dtype=torch.float64)
[3. 3. 3.] tensor([3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [59]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4.] tensor([3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [60]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([[ 1.7870,  1.1076, -0.0715,  0.8834, -0.0170],
        [-0.4453,  0.1922,  2.1975, -0.3700, -1.7575],
        [ 0.1676,  1.4900,  1.2908,  1.6442,  4.9300],
        [ 0.8756,  1.2953,  3.4197,  2.6456,  0.6913],
        [-0.5147,  2.9457, -0.2904, -1.3495, -1.0689]], device='cuda:0')
tensor([[ 1.7870,  1.1076, -0.0715,  0.8834, -0.0170],
        [-0.4453,  0.1922,  2.1975, -0.3700, -1.7575],
        [ 0.1676,  1.4900,  1.2908,  1.6442,  4.9300],
        [ 0.8756,  1.2953,  3.4197,  2.6456,  0.6913],
        [-0.5147,  2.9457, -0.2904, -1.3495, -1.0689]], dtype=torch.float64)
