## Part 1 - Tensor Basics

In [1]:
import torch

In [2]:
x = torch.randn(5)
print(x)

tensor([-0.6016,  0.3637, -0.0168,  1.6182,  0.9072])


In [3]:
x = torch.arange(1,3)
print(x)

tensor([1, 2])


In [4]:
x.view(1,2)

tensor([[1, 2]])

In [10]:
y = torch.arange(1,4)
y = y.view(3,1)

In [11]:
x = x.view(1,2)
print(x)
print(y)
print(x+y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [17]:
torch.add(x, y, out=out)

NameError: name 'out' is not defined

## part 2 - torch.tensor : autograd

In [40]:
import torch

In [50]:
x = torch.ones(1, device="cuda", requires_grad=True)

In [51]:
y = x ** 2;
z = 3 * y + 2;

In [52]:
print (y)
print (z)

tensor([1.], device='cuda:0', grad_fn=<PowBackward0>)
tensor([5.], device='cuda:0', grad_fn=<AddBackward0>)


In [53]:
print (y.grad_fn)
print (z.grad_fn)

In [54]:
z.backward()
print(x.grad)
x.grad.data.zero_()

tensor([6.], device='cuda:0')


tensor([0.], device='cuda:0')

##### combine above steps together

In [56]:
y = x ** 2;
z = 3 * y + 2;
z.backward(x)
print(x.grad)
x.grad.data.zero_()

tensor([6.], device='cuda:0')


tensor([0.], device='cuda:0')

##### above we use a scalar data to do autograd computation, below we will use a tensor with multiple dimension;

In [57]:
x = torch.ones((3,3), device="cuda", requires_grad=True)
y = x ** 2 + 3 * x + 8;
z = 3 * (y ** 3)
out = z.sum()
out.backward()
print(x.grad)
x.grad.data.zero_()

tensor([[6480., 6480., 6480.],
        [6480., 6480., 6480.],
        [6480., 6480., 6480.]], device='cuda:0')


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')